---
title: "Phylogenetic Diversity - Communities"
author: "Z620: Quantitative Biodiversity, Indiana University"
date: "February 26, 2015"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## Pruning trees to only include species from phylogeny (phy) that are present in the community (comm)
```{r}
# # Prune a phylogenetic tree to include only species present
# # It's not clear that we will need the `prune.sample` function 
# # Need to make sure OTU names in comm match names in phy
# prunedphy <- prune.sample(comm, phy) 
# 
# par(mfrow = c(2, 3)) # figure with 2 rows and 3 columns
# 
# for (i in row.names(com)) {
#   plot(prunedphy, show.tip.label = FALSE, main = i) 
#   tiplabels(tip = which(prunedphy$tip.label %in% names(which(com [i, ] > 0))), pch = 19, cex = 2)
#   }
```

## Example from Picante Vignette: Eventually will be delted, but not yet...

```{r}
# From Picante Vignette (http://goo.gl/EYOZ55)
data(phylocom)
names(phylocom)

# We need to make sure that the names associate with the tree match up with the names in the site-by-species matrix in `comm` below. 
phy.eg <- phylocom$phy

# Community Data: Site-by-Species Matrix
comm.eg <- phylocom$sample
```