---
title: "Week2_Supplementary"
author: "Jay T. Lennon"
date: "January 17, 2015"
output: pdf_document
---
Another commonly used estimator is **ACE**, which stands for abundance-based coverage estimator. 
While Chao1 makes inferences based on the number of singletons and doubletons, ACE implements a threshold to look at the abundance of other *rare* species. 
By convention, ACE defines rare species as taxa that have 10 or fewer individuals.
Consequently, whether one uses the ACE estimator depends on whether one's samples tend to have many species of few individuals.
If so, the ACE estimator may ignore the majority of sampled species.
Now we will write a function for the ACE estimator:

```{r}
S.ace <- function(x = "", thresh = 10){ 
  x <- x[x>0]                           # excludes zero-abundance taxa
  S.abund <- length(which(x > thresh))  # richness of abundant taxa
  S.rare  <- length(which(x <= thresh)) # richness of rare taxa
  singlt  <- length(which(x == 1))      # number of singleton taxa
  N.rare  <- sum(x[which(x <= thresh)]) # abundance of rare individuals
  C.ace   <- 1 - (singlt / N.rare)      # coverage (prop non-singlt rare inds)
  i       <- c(1:thresh)                # threshold abundance range
  count   <- function(i, y){            # counter to go through i range
    length(y[y == i])
  }
  a.1     <- sapply(i, count, x)        # number of individuals in richness i richness classes
  f.1     <- (i * (i - 1)) * a.1        # k(k-1)kf sensu Gotelli
  G.ace   <- (S.rare/C.ace)*(sum(f.1)/(N.rare*(N.rare-1)))
  S.ace   <- S.abund + (S.rare/C.ace) + (singlt/C.ace) * max(G.ace,0) 
  return(S.ace)
}
```

_Notes_
+ `estimateR` is a function in the `vegan` pakcage 
+ It will spit out observed richness, along with Chao1, ACE, and their associated confidence intervals. 
+ You can look more into the code in R packages using commands like this: vegan:::estimateR.default
+ Try it out!