---
title: "Week 8 --- Git On"
author: "Z620: Quantitative Biodiversity, Indiana University"
date: "March 6, 2015"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW
Migrating to github.com with licensed code, an informative README file, and a website(?).

After completing this exercise you will know how to:

1.  Make a repo within the IU GitHub system
2.  Craft README.md and R source files
3.  Open a github.com account (not restricted to IU)
4.  Properly license your work, i.e., open but copyrighted
5.  Request private repos from github.com

## 1) MAKING a REPO
So far this semester you have been working with a repository that was created 



## 2) CREATE SOURCE CODE FILE
Last week we learned the benefit of using a R source code file. 
As a reminder, a source code file has user-defined functions that are required for certain analyses.
The benefit of source files is that they contain "vetted" code that can be used across multiple projects. 
Last week, that file contained code for importing files created by the popular community sequencing software `mothur` (http://www.mothur.org/).
This week, we will make our own source code file containing code (functions) that we created during QB.

1. Create a blank R file. 
2. In your menu bar, choose File > New File > R Script (alternatively, Ctrl + Shift + N)
3. Add a file header.
This should be a commented out section that give all of the required information for users to use this script.
Additionally, this may contain notes for the user.

Here is an example header:

```{sh}
################################################################################
#                                                                              #
# Quantitative Biodiversity Functions Source Code                              #
#                                                                              #
# Written by: Student X                                                        #
#                                                                              #
# Last update: 2015/03/06                                                      #
#                                                                              #
# Notes:                                                                       #  
#                                                                              #
################################################################################
```

There are a few things to notice about the header:
1. The comment character (#) prevents R from interpreting the information in the header
2. The header is formatted for stylystic purposes; it is 80 characters wide (as should your file), and it is boxed off using comment characters. 
There are other ways of stylizing your header, this is just one option.

4. Add content
A. The first thing you will want to do is add and require commands.
This is a bit different than before because we need to make sure that the packages are installed.
By default, the following code will try to load a package and will then install if not found.

```{sh}
require("vegan")||install.packages("vegan");require("vegan")

```
You can cusotmize this code for any package that you want loaded for our source file

B. Add functions:
The major goal this week is to make a source file that contains all of the functions we wrote this semester.
So now you are going to populate this file with those function.
Go through all of your assignments and find the functions you want to save.
Copy those functions into this new source file. 
Add comments about each function before the code.
For example:

```{sh}
# My_Function: has some cool code
# Inputs: x, y, z

My_Function <- function(x, y, z){
  ...
}

```

Add as many functions are you want. 

## 2) CREATE A README.md FILE
In the beginning of the course, we had you edit a README.md file, which gave us some information about you.
In general, README files provide:

* 1.) More or less detailed information on the content of a repository
* 2.) The version of programs and software, data, etc. needed to run the code
* 3.) Contact information for the owner of the repository (e.g., email)
* 4.) Potential bugs  

This last one is commonplace among people who develop and distribute software (e.g. ecologists who develop R packages) and among folks who engage seriously in reproducible science.

## 2) MIGRATING TO GITHUB.COM
notes, add:
1. how to setup
2. create a repo...GitHub will ask whether you want to add a README.md.
3. add a license...should the licensing section be moved here, as a subsection?
4. add source file


## 3) LICENSING YOUR CODE (this should come after "MIGRATING" because you can't automatically license code on IU's GitHub. If you figure out how to add a license, it won't mean much because IU probably owns whatever you put on their Enterprise, i.e., IU rights supercede your license)

When setting up public repositories on GitHub, you will want to license your work because it will be in the public domain. 
Licenses are what allow you to establish the right to waive responsibilities and liabilities, to attract copyright, and to legally establish intellectual primacy.
Licensing allows us to be visible, transparent, and fearless professionals; protected by putting our ideas and work into the public domain while maintaining rights and restrictions to (re)use and (re)distribution.

GitHub offers a broad selection of licenses that range from short and tidy (MIT) to the thorough but lengthy (GPL V3); see http://choosealicense.com/.
9 Simple ways to make it easier to (re)use your data. There's lots of goodies of in it, the repo which is found here:  https://github.com/weecology/data-sharing-paper.


